# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  deploy:
    machine: true

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      IMAGE_NAME_REST: easypnr/easypnr-rest
      IMAGE_NAME_WEB: easypnr/easypnr-web

    steps:
      - checkout
      - run: docker info
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          ls -la
          find . -name Dockerfile
      - run: ./gradle build bootBuildImage
      - run: docker images list
      - run: docker push hedvig-test

workflows:
  version: 2
  myWorkFlow:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master